### ISSUE TITLE
Allow sharing route and settings via URL

### ISSUE THREAD

**Issue by not-my-profile** [gis-ops/valhalla-app#30] opened 2022-08-25 07:35 UTC
It would be very handy if you could share a route with specific settings via an URL.
E.g. if Valhalla yields an unexpected route, you could share the URL for demonstration when reporting the issue at valhalla.

**Comment by nilsnolde** [comment] 2022-09-28 18:43
To some degree this is implemented, but not more than waypoints and costing model currently. Definitely worth a PR:) Would you be up for that?

**Comment by nilsnolde** [comment] 2022-09-28 18:50
actually it's a duplicate of #1 :)

**Closed by nilsnolde** 2022-09-28 18:50 UTC
